name: test
run-name: ${{ github.actor }} is testing

# on:
#   push:
#     # Pattern matched against refs/tags
#     tags:        
#       - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Test
        run: |
          mvn test

